language: node_js

node_js:
  - "14.15.5"

script:
  - node --version
  - npm install
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$TODO_LIST"
  local_dir: build
  keep_history: true
  on:
    branch: master

git:
  depth: 5
